In [9]:
import torch
import numpy as np

print(torch.__version__)

1.13.1+cu117


# 텐서(Tensor)

- 배열(array)와 행렬(matrix)와 매우 유사한 자료 구조이며 PyTorch에서는 텐서를 사용하여 모델의 입출력, 모델의 매개변수를 인코드 한다.
    
    
- 텐서는 Numpy의 ndarray와 유사하지만 차이점은 GPU를 통해 하드웨어 가속이 가능하다.
- 또한 Numpy array와 메모리를 공유할 수 있다.

## 텐서 초기화

### 데이터로부터 직접 생성하기

In [8]:
data = [[1,2], [3,4]]

x_data = torch.tensor(data)

print(x_data)
print(x_data.type)
print(x_data.dtype)

tensor([[1, 2],
        [3, 4]])
<built-in method type of Tensor object at 0x7fb47c604a40>
torch.int64


### NumPy 배열로부터 생성하기

In [11]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(x_np)
print(x_np.type)
print(x_np.dtype)

tensor([[1, 2],
        [3, 4]])
<built-in method type of Tensor object at 0x7fb47c5ac720>
torch.int64


### 다른 텐서로부터 생성하기

- 명시적으로 재정의 하지 않는다면 인자로 주어진 텐서의 dtype, shape를 유지한다.

In [18]:
x_ones = torch.ones_like(x_data) # 속성을 유지
print(f'Ones Tensor: \n {x_ones}\n')
# 유지했기에 shape와 dtype이 유지된다.

x_rand = torch.rand_like(x_data, dtype=torch.float) # dtype을 float으로 변경한다.
print(f'Random Tensor: \n {x_rand} \n')
print(f'Random Tensor의 dtype 변경 history:\n {x_data.dtype} -> {x_rand.dtype}')
# dtype을 명시했기에 int64였던 dtype이 float32로 변경되었다.

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.4512, 0.3598],
        [0.3679, 0.5155]]) 

Random Tensor의 dtype 변경 history:
 torch.int64 -> torch.float32


### 무작위 또는 상수 값을 사용하기
- `shape`은 텐서의 차원을 나타내는 `tuple`로 출력 텐서의 차원을 결정한다.

In [21]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2973, 0.7199, 0.6453],
        [0.1614, 0.2390, 0.0904]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성(Attribute)
- 텐서의 속성은 텐서의 `Shape`, `Dtype` 및 어느 장치에 저장되는 지를 나타낸다.

In [24]:
tensor = torch.rand(3,4)

print(f"텐서의 형태: {tensor.shape}")
print(f"텐서의 데이터 타입: {tensor.dtype}")
print(f"사용하고 있는 디바이스: {tensor.device}")

텐서의 형태: torch.Size([3, 4])
텐서의 데이터 타입: torch.float32
사용하고 있는 디바이스: cpu


## 텐서 연산(Operation)

- `전치(Transposing)`, `인덱싱(Indexing)`, `슬라이싱(Slicing)`, `수학 계산`, `선형 대수`, `임의 샘플링` 등 100가지 이상의 텐서 연산이 있다.
    
- 각 연산들은 GPU 에서 실행이 가능하다.
    
- 설정하지 않는다면 기본적으로 CPU로 생성된다. `.to` 메서드를 이용하여 GPU의 가용성을 확인한 뒤 GPU로 명시적 이동이 가능하다.

In [25]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [27]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### 텐서 합치기
- `torch.cat` 을 사용하여 텐서를 연결 할 수 있다.
- 이와 미묘하게 다른 텐서 결합 연산인 `torch.stack`도 있다.

In [36]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print()
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [39]:
t1 = torch.stack([tensor, tensor, tensor], dim=0)
t2 = torch.stack([tensor, tensor, tensor], dim=1)

print(t1)
print()
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


### 산술 연산

In [40]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### 단일-요소(single-element) 텐서 
- 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, `item()` 을 사용하여 `Python 숫자 값으로 변환`할 수 있습니다:

In [42]:
agg = tensor.sum() # PyTorch 텐서 형태
agg_item = agg.item() # Python float 형태
print(agg_item, '\n', type(agg_item))

12.0 
 <class 'float'>


### 바꾸기 연산 (inplace)
- `_`라는 `접미사` 를 가지며 inplace 연산을 진행한다.

In [46]:
print(f'{tensor}\n')
tensor.add_(5)
print(tensor) # inplace 연산으로 지정해주지 않아도 연산이 적용되었다.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환
- CPU 상의 텐서와 NumPy는 메모리 공간을 공유하기에 하나를 변경하면 다른 하나도 변경된다.

In [48]:
t = torch.ones(5)
print(f'tensor: {t}')
n = t.numpy()
print(f'numpy: {n}')

tensor: tensor([1., 1., 1., 1., 1.])
numpy: [1. 1. 1. 1. 1.]


In [49]:
t.add_(1) # inplace 연산을 적용하여 모두 변한것을 볼 수 있다.
print(f'tensor: {t}')
print(f'numpy: {n}')

tensor: tensor([2., 2., 2., 2., 2.])
numpy: [2. 2. 2. 2. 2.]


In [50]:
n = np.ones(5)
t = torch.from_numpy(n)

In [56]:
np.add(n, 1, out=n)
print(f'tensor: {t}')
print(f'numpy: {n}')

tensor: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
numpy: [2. 2. 2. 2. 2.]


In [57]:
np.add(n, 3, out=n)
print(f'tensor: {t}')
print(f'numpy: {n}')

tensor: tensor([5., 5., 5., 5., 5.], dtype=torch.float64)
numpy: [5. 5. 5. 5. 5.]


In [58]:
np.add(n, -4, out=n)
print(f'tensor: {t}')
print(f'numpy: {n}')

tensor: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
numpy: [1. 1. 1. 1. 1.]
